DROP TABLE IF EXISTS `feedbacks`;
CREATE TABLE `feedbacks`(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	feedback TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS `products`;
CREATE TABLE `products`(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	price integer NOT NULL,
	thumb_img_path VARCHAR(255) NOT NULL,
	img_path VARCHAR(255) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

