DROP TABLE IF EXISTS images;
CREATE TABLE images(
	id SERIAL PRIMARY KEY,
	path VARCHAR(255) NOT NULL,
	thumb_path VARCHAR(255) NOT NULL,
	size INTEGER NOT NULL,
	view_counter INTEGER UNSIGNED DEFAULT 0,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

